#------------------------------------------------------------------------------
# PROJECT: GENDER PAY GAP STARTING POINTS AND LIFE COURSE DIVERGENCE
# FILE: GENERATING ASEC ANALYTIC SAMPLE FROM RAW IPUMS DATA
# AUTHOR: NINO CRICCO
#------------------------------------------------------------------------------
source("jobs/0-helperfunctions.R")
#------------------------------------------------------------------------------
# READ IN RAW DATA
#------------------------------------------------------------------------------
# DDI codebook to read in raw IPUMS data

# To load data, you must download both the extract and DDI from IPUMS
# also set the wd to the folder with these files (or change the path below).

ddi_asec <- ipumsr::read_ipums_ddi("raw_data/cps_00025.xml")
data_asec <- ipumsr::read_ipums_micro(ddi_asec)

#------------------------------------------------------------------------------
# RECODING RAW DATA
#------------------------------------------------------------------------------
# Read in CPI adjustment spreadsheet
# Generated by IPUMS, accesible at https://cps.ipums.org/cps/cpi99.shtml
cpi99 <- read_csv("raw_data/cpi99.csv")

# Creating the analytic sample
analytic_sample <- data_asec %>%
  left_join(., cpi99, by = c("YEAR" = "year")) %>%
  mutate(
    BIRTHYEAR = YEAR-AGE,  # Estimating Birth Cohort using survey year & age- Rs could also belong to prior BC 
    BIRTHYEAR_DECADES = case_when(
      BIRTHYEAR %in% c(1927:1936) ~ "1927-1936",
      BIRTHYEAR %in% c(1937:1946) ~ "1937-1946",
      BIRTHYEAR %in% c(1947:1956) ~ "1947-1956",
      BIRTHYEAR %in% c(1957:1966) ~ "1957-1966",
      BIRTHYEAR %in% c(1967:1976) ~ "1967-1976",
      BIRTHYEAR %in% c(1977:1986) ~ "1977-1986",
      BIRTHYEAR %in% c(1987:1996) ~ "1987-1996"),
    FEMALE = ifelse(SEX == 2, "Women", "Men"),
    EDUC = ifelse(EDUC == 999, NA, EDUC),
    EDUC2 = ifelse(EDUC >= 110, "BA+", "<BA"),
    # We use Race and Hispanic/Latino origin/descent to code for Race/Ethnicity
    # Starting in 2003, CPS allowed Rs to select more than 1 Race, expanding the number of codes
    # We code Rs who report >1 Race, and who do not report being Black, White, or Latino as "Other"
    RACEETH = case_when(
      HISPAN %!in% c(0, 901, 902) ~ "Latino",
      RACE == 200 ~ "Black",
      RACE == 100 ~ "White",
      TRUE ~ "Other"), 
    # We use annual/wage salary income as our main outcome measure
    INCWAGE = ifelse(INCWAGE == 99999999, NA, INCWAGE),
    # Adding IPUMS adjustment factor to convert to 2023 dollars
    # from here: https://cps.ipums.org/cps/cpi99.shtml
    INCWAGE = INCWAGE *cpi1999 * 1.829) %>%
  filter(complete.cases(ASECWT)) %>% # Selecting only individuals w/ + weights
  filter(AGE >= 25 & AGE <= 55) # Age Restrictions

#------------------------------------------------------------------------------
# WRITING ANALYTIC SAMPLE TO THE CLEAN DATA DIRECTORY
#------------------------------------------------------------------------------
write_rds(analytic_sample, "clean_data/analytic_sample_asec.rds")
write_csv(analytic_sample, "clean_data/analytic_sample_asec.csv")
