#------------------------------------------------------------------------------
# PROJECT: GENDER PAY GAP STARTING POINTS AND LIFE COURSE DIVERGENCE
# FILE: GENERATING ORG ANALYTIC SAMPLE FROM RAW IPUMS DATA
# AUTHOR: NINO CRICCO
#------------------------------------------------------------------------------
# NOTE: To load data, you must download both the extract's data and the DDI and 
# also set the wd to the folder with these files (or change the path below).

source("jobs/0-helperfunctions.R")

#------------------------------------------------------------------------------
# READ IN RAW DATA
#------------------------------------------------------------------------------
# DDI codebook to read in raw IPUMS data
ddi_monthly <- ipumsr::read_ipums_ddi("raw_data/cps_00023.xml")

data_monthly <- ipumsr::read_ipums_micro(
  ddi_monthly, 
  vars = c(
    "YEAR", # Survey Year
    "MISH", # Month in CPS sample, used to identify ORG interview months 
    "AGE", # Age
    "IND1990", # 1990 Industry codes
    "CLASSWKR", # Indicates whether employer is self-employed, public/private sector, armed forces, or worked without pay
    "SEX", # Sex
    "EDUC", # IPUMS educational attainment recode
    "ELIGORG", # Indicator for wtr R was eligible for ORG (in month 4 or 8 of CPS interview + wage or salary worker)
    "HOURWAGE", # R earnings per-hour in current job if R paid by the hour (2 in PAIDHOUR)
    "HOURWAGE2", # Like above, but w/rounding changes for all months and top-code changes for months after 04/23
    "EARNWEEK", # R earnings per week at current job before deductions
    "EARNWEEK2", # # Like above, but w/rounding changes for all months
    "PAIDHOUR", # Indicator for wtr R paid by the hour for their current job
    "UHRSWORK1", # Usual hours per week R reports being at their main job, monthly survey
    "UHRSWORKORG", # Usual hours per week R reports at main job, for ORG hourly workers only (hours worked at hourly rate)
    "WKSTAT", # Census recode for part-time or full-time employment status
    "EARNWT", # Weight for the ORG
    "HISPAN", # Hispanic/Spanish/Latino ancestry, heritage, country of birth
    "RACE", # Racial category
    "MARST", # Current marital status
    "NATIVITY" # Native or foreign born
    )) %>%
  filter(YEAR >= 1982, YEAR <= 2024) %>% # Selecting observation years
  filter(MISH %in% c(4, 8)) %>% # Selecting months eligible for ORG interview
  filter(AGE >= 25 & AGE <= 55) # Selecting age window

#------------------------------------------------------------------------------
# RECODING RAW DATA
#------------------------------------------------------------------------------
# Read in CPI adjustment spreadsheet
# Generated by IPUMS, accesible at https://cps.ipums.org/cps/cpi99.shtml
cpi99 <- read_csv("raw_data/cpi99.csv")

analytic_sample <- data_monthly %>% 
  # Merging in CPI inflation adjustment 
  left_join(., cpi99, by = c("YEAR" = "year")) %>%
  mutate(
    BIRTHYEAR = YEAR-AGE, 
    FEMALE = ifelse(SEX == 2, "Women", "Men"),
    EDUC = ifelse(EDUC == 999, NA, EDUC),
    EDUC2 = ifelse(EDUC >= 110, "BA+", "<BA"),
    HOURWAGE = na_codes(HOURWAGE2, 999.99),
    HOURWAGE2 = na_codes(HOURWAGE2, 999.99),
    EARNWEEK = na_codes(EARNWEEK, 9999.99), 
    EARNWEEK2 = na_codes(EARNWEEK2, 999999.99), 
    UHRSWORKORG = na_codes(UHRSWORKORG, c(998, 999)), 
    UHRSWORK1_HRSVARY_FLAG = ifelse(UHRSWORK1 == 997, 1, 0), # Indicator for whether R reported hours vary
    UHRSWORK1 = na_codes(UHRSWORK1, c(997, 999)),
    WKSTAT_SUM = case_when(WKSTAT %in% c(10:15) ~ "ft", 
                           WKSTAT %in% c(20:42) ~ "pt", 
                           WKSTAT %in% c(50, 60)~ "unemp"), 
    EARNWT = EARNWT/12,
    RACEETH = case_when(HISPAN %!in% c(0, 901, 902) ~ "Latino",
                        RACE == 200 ~ "Black",
                        RACE == 100 ~ "White",
                        TRUE ~ "Other"), 
    MARRIED = case_when(MARST %in% c(1,2) ~ "married", 
                        MARST == 6 ~ "never.married", 
                        TRUE ~ "prev.married"), 
    FBORN = factor(ifelse(NATIVITY == 5, 1, 0))) %>%
  # Identifying top-code values by year
  group_by(YEAR, MISH) %>%
  mutate(across(
    c(EARNWEEK, EARNWEEK2),
    list(TOPCODE = ~ max(.x, na.rm = TRUE),
         TOPCODE_FLAG = ~ as.integer(.x == max(.x, na.rm = TRUE))),
    .names = "{.col}_{.fn}"
  )) %>%
  ungroup()

#------------------------------------------------------------------------------
# RECODING MAIN EARNINGS VARIABLES
#------------------------------------------------------------------------------

# I think we need some more commentary, drawing from the Schmitt paper,
# about why we’re doing what we’re doing. At the start of this section of code, 
# we could note that we follow the guidance in Schmitt and include the link 
# (you already have the link at line 106). We could also include this overall quote: 
# “The analysis here suggests that the a [sic] consistent and robust hourly wage series for the full
#1979-2002 period: (1) uses a log-normal imputation to adjust for top-coding; (2) excludes data
#below $1 and above $100 per hour (in constant 2002 dollars); (3) excludes overtime, tip, and
#commission earnings for hourly paid workers; and (4) uses a simple procedure to impute usual
#weekly hours for those who report their "hours vary" after 1994 (though the effects of not doing
# this are likely to be minor). For the period 1994-2002, the best hourly wage series follows the
# same procedure, but includes overtime, tips, and commissions for workers that report their
# earnings by the hour.” I have some more detailed comments below

# From IPUMS documentation
# https://cps.ipums.org/cps-action/variables/EARNWEEK#description_section
# Interviewers asked directly about total weekly earnings and also collected 
# information about the usual number of hours worked per week and the hourly 
# rate of pay at the current job. The figure given in EARNWEEK is the higher of 
# the values derived from these two sources:
#   1) the respondent's answer to the question, "How much do you usually earn
#   per week at this job before deductions?" or 
#   2) for workers paid by the hour (and coded as "2" in PAIDHOUR), the 
#   reported number of hours the respondent usually worked at the job,
#   multiplied by the hourly wage rate given in HOURWAGE.
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Procedure to impute hours worked for respondents who report hours vary after
# 1994 CPS questionnaire redesign
# see: https://ceprdata.s3.amazonaws.com/data/cps/CEPR_ORG_Wages.pdf
#------------------------------------------------------------------------------

# Diagnostics figure to show what % of ORG eligible respondents report 
# "hours vary" by year and sex
fig_diag_hrsvary <- analytic_sample %>%
  filter(ELIGORG == 1) %>%
  group_by(FEMALE, YEAR) %>%
  summarise(share_hrsvary = wtd.mean(UHRSWORK1_HRSVARY_FLAG, weight = EARNWT)) %>%
  ggplot(aes(x = YEAR, y = share_hrsvary, linetype = FEMALE)) +
  geom_line() +
  theme_bw() +
  labs(title = "Diagnostics Plot: Workers Reporting Hours Vary, CPS Outgoing Rotation Group",
       y = "Share", x = "Year") +
  theme(legend.position = "bottom", 
        plot.title = element_text(hjust = .5),
        legend.title = element_blank()) +
  geom_vline(xintercept = 1994, color = "red", linetype = "dashed")

# Among those with UHRSWORK1_HRSVARY_FLAG == 0, 
# fit separate models by FEMALE and WKSTAT_SUM predicting UHRSWORK1 
# as a function of age, race, education, marital status, and nativity

# First split data into estimation and prediction samples
hrsvary_estimation <- analytic_sample %>%
  filter(UHRSWORK1_HRSVARY_FLAG != 1)

# Get a sense for missingness for reasons other than "Hours vary"
# Note: When we filter to ELIGORG eligibile respondents, there is no missingness
# beyond hours vary, but at this stage we keep all respondents in the ORG
# months even if they are not ORG eligible for later selection into 
# ORG prediction models
length(which(is.na(hrsvary_estimation$UHRSWORK1)))/dim(hrsvary_estimation)[1]

# Create nested dataframes by group for men, women by reported ft/pt status
model_hrsvary <- hrsvary_estimation %>%
  filter(ELIGORG == 1) %>%
  group_by(FEMALE, WKSTAT_SUM) %>%
  nest() %>%
  # Fit models for each group
  mutate(
    model = map(
      data, ~ lm(UHRSWORK1 ~ AGE + RACEETH + MARRIED + FBORN + EDUC, data = .x))
  )

# For workers who report hours vary, benerate predicted hours
hrsvary_data <- analytic_sample %>%
  filter(UHRSWORK1_HRSVARY_FLAG == 1) %>%
  group_by(FEMALE, WKSTAT_SUM) %>%
  nest() %>%
  # Join with model data to get appropriate models
  left_join(model_hrsvary %>% select(-data), by = c("FEMALE", "WKSTAT_SUM")) %>%
  # Generate predictions
  mutate(predictions = map2(model, data, predict)) %>%
  select(-model) %>%
  unnest(cols = c(data, predictions))

# Combine dataframes, workers reporting hours + workers reporting hours vary
analytic_sample_hrsvary <- bind_rows(
  hrsvary_estimation %>% mutate(UHRSWORK1_PRED = UHRSWORK1),
  hrsvary_data %>% mutate(UHRSWORK1_PRED = predictions)) %>%
  arrange(row_number()) %>%
  # Additional variable capping hours worked (obs or predicted) at 40
  mutate(UHRSWORK1_PRED_CAP = ifelse(UHRSWORK1_PRED > 40, 40, UHRSWORK1_PRED))

# Diagnostic plot comparing mean hours worked with list-wise deletion of workers
# reporting hours vary vs. imputing hours worked

fig_hrsvary_pred <- analytic_sample_hrsvary %>%
  filter(ELIGORG == 1) %>%
  group_by(FEMALE, YEAR) %>%
  summarise(UHRSWORK1_PRED = wtd.mean(UHRSWORK1_PRED, weight = EARNWT), 
            UHRSWORK1 = wtd.mean(UHRSWORK1, weight = EARNWT)) %>%
  gather(key, value, -c(FEMALE, YEAR)) %>% 
  ggplot(aes(x = YEAR, y = value, linetype = key)) +
  geom_line() +
  theme_bw() +
  facet_wrap(~FEMALE) +
  labs(title = "Diagnostics Plot: Mean Usual Hours Worked, List-wise Deletion 
       and Imputation, CPS Outgoing Rotation Group",
       y = "Share", x = "Year") +
  theme(legend.position = "bottom", 
        plot.title = element_text(hjust = .5),
        legend.title = element_blank()) +
  geom_vline(xintercept = 1994, color = "red", linetype = "dashed")

ggsave("figures/draft_paper/diagnostic_plots/hoursvary.pdf",
       grid.arrange(fig_diag_hrsvary, fig_hrsvary_pred, ncol = 1),
       width = 10, height = 10, dpi = 500, units = "in")

#------------------------------------------------------------------------------
# Procedure to adjust for changes in top-coding using log-normal distribution 
# to estimate mean and variance above the topcode 
# see: https://ceprdata.s3.amazonaws.com/data/cps/CEPR_ORG_Wages.pdf
#------------------------------------------------------------------------------

# Diagnostic plot, share of workers reporting weekly earnings above the topcode
fig_diag_topcode <- analytic_sample_hrsvary %>%
  filter(ELIGORG == 1) %>%
  group_by(FEMALE, YEAR) %>%
  summarise(
    SHARE_TOPCODED_EARNWEEK = wtd.mean(
      EARNWEEK_TOPCODE_FLAG, weight = EARNWT), 
    SHARE_TOPCODED_EARNWEEK2 = wtd.mean(
      EARNWEEK2_TOPCODE_FLAG, weight = EARNWT)) %>%
  gather(key, value, -c(YEAR, FEMALE)) %>%
  ggplot(aes(x = YEAR, y = value, color = FEMALE,
             linetype = key)) +
  geom_line() +
  geom_point() +
  theme_bw() +
  labs(title = "Diagnostics Plot: Workers w/ Top-Coded Weekly Earnings, ORG",
       y = "Share", x = "Year") +
  theme(legend.position = "bottom", 
        plot.title = element_text(hjust = .5),
        legend.title = element_blank()) +
  geom_vline(xintercept = 1989, color = "red", linetype = "dashed") +
  geom_vline(xintercept = 1998, color = "red", linetype = "dashed") +
  geom_vline(xintercept = 2023, color = "red", linetype = "dashed")

analytic_sample_recoded_topcode <- analytic_sample_hrsvary %>% 
  group_by(YEAR, MISH) %>%
  mutate(
    # For EARNWEEK
    mu1 = ifelse(EARNWEEK_TOPCODE_FLAG == 1,
                 mean(log(EARNWEEK), na.rm = TRUE), NA_real_),
    sd1 = ifelse(EARNWEEK_TOPCODE_FLAG == 1,
                 sd(log(EARNWEEK),  na.rm = TRUE), NA_real_),
    lt1 = log(EARNWEEK_TOPCODE),
    t1_1 = exp(mu1 + sd1^2 / 2),
    t2_1 = 1 - pnorm((lt1 - mu1 - sd1^2) / sd1),
    t3_1 = 1 - pnorm((lt1 - mu1) / sd1),
    EARNWEEK_TC = ifelse(EARNWEEK_TOPCODE_FLAG == 1,
                       t1_1 * t2_1 / t3_1, EARNWEEK),
    # SAME PROCESS FOR EARNWEEK2
    mu2 = ifelse(EARNWEEK2_TOPCODE_FLAG == 1,
                 mean(log(EARNWEEK2), na.rm = TRUE), NA_real_),
    sd2 = ifelse(EARNWEEK2_TOPCODE_FLAG == 1,
                 sd(log(EARNWEEK2),  na.rm = TRUE), NA_real_),
    lt2 = log(EARNWEEK2_TOPCODE),
    t1_2 = exp(mu2 + sd2^2 / 2),
    t2_2 = 1 - pnorm((lt2 - mu2 - sd2^2) / sd2),
    t3_2 = 1 - pnorm((lt2 - mu2) / sd2),
    EARNWEEK2_TC = ifelse(EARNWEEK2_TOPCODE_FLAG == 1,
                        t1_2 * t2_2 / t3_2,
                        EARNWEEK2)
    ) %>% 
  ungroup() %>% 
  select(-starts_with("mu"), -starts_with("sd"),
         -starts_with("lt"), -starts_with("t1_"),
         -starts_with("t2_"), -starts_with("t3_"))

# Diagnostic plot, mean earnings w/topcode vs. adjusting topcode
fig_mean_earnings_topcode_adj <- analytic_sample_recoded_topcode %>%
  filter(ELIGORG == 1) %>%
  group_by(FEMALE, YEAR) %>%
  summarise(EARNWEEK2_TC = wtd.mean(EARNWEEK2_TC, weight = EARNWT), 
            EARNWEEK2 = wtd.mean(EARNWEEK2, weight = EARNWT)) %>%
  gather(KEY, VALUE, -c(FEMALE, YEAR)) %>%
  ggplot(aes(x = YEAR, y = VALUE, linetype = KEY)) +
  geom_line() +
  geom_point() +
  theme_bw() +
  facet_wrap(~FEMALE) + 
  labs(title = "Diagnostics Plot: Mean Weekly Earnigns w/ Top-Code Adjustment, ORG",
       y = "Weekly Earnigns", x = "Year") +
  theme(legend.position = "bottom", 
        plot.title = element_text(hjust = .5),
        legend.title = element_blank()) +
  geom_vline(xintercept = 1989, color = "red", linetype = "dashed") +
  geom_vline(xintercept = 1994, color = "red", linetype = "dashed") +
  geom_vline(xintercept = 1998, color = "red", linetype = "dashed")

ggsave("figures/draft_paper/diagnostic_plots/topcode.pdf",
       grid.arrange(fig_diag_topcode, fig_mean_earnings_topcode_adj, ncol = 1),
       width = 8, height = 8, dpi = 500, units = "in")

# For the period 1979-2002, the most consistent and
# robust hourly wage series:  (2) excludes
# data below $1 and above $100 per hour (in constant 2002 dollars); (3) excludes overtime, tip,
# and commission earnings for hourly paid workers; and (4) uses a simple procedure to impute
# usual weekly hours for those who report their "hours vary" after 1994. For the period 1994-2002,
# the best hourly wage series follows the same procedure, but includes overtime, tips, and
# commissions for workers that report their earnings by the hour.

analytic_sample_org <- analytic_sample_recoded_topcode %>%
  mutate(
    # Raw IPUMS values with NA recoding
    HOURWAGE_RAW = HOURWAGE,
    EARNWEEK_RAW = EARNWEEK,
    HOURWAGE2_RAW = HOURWAGE2,
    EARNWEEK2_RAW = EARNWEEK2,
    # CPI- adjusted values
    HOURWAGE = HOURWAGE * cpi1999 * 1.829, # Multiplying by factor to get 2023 dollars
    EARNWEEK = EARNWEEK * cpi1999 * 1.829,
    HOURWAGE2 = HOURWAGE2 * cpi1999 * 1.829, 
    EARNWEEK2 = EARNWEEK2 * cpi1999 * 1.829,
    # Top-coded 
    EARNWEEK_TC = EARNWEEK_TC * cpi1999 * 1.829,
    EARNWEEK2_TC = EARNWEEK2_TC * cpi1999 * 1.829,
    # Using Wage for hourly workers, Weekly Earnings/ Usual Weekly hours for rest
    # Note: this variable excludes tips, overtime, and commissions for hourly workers,
    # but includes them for weekly workers
    EARNHRLY_EXCTIPS = case_when(PAIDHOUR == 2 ~ HOURWAGE, 
                         UHRSWORK1 == 0 ~ NA,
                         PAIDHOUR != 2 ~ EARNWEEK/UHRSWORK1),
    EARNHRLY2_EXCTIPS = case_when(PAIDHOUR == 2 ~ HOURWAGE2, 
                              UHRSWORK1 == 0 ~ NA,
                              PAIDHOUR != 2 ~ EARNWEEK2/UHRSWORK1),
    # Using predicted weekly hours among non-hourly workers to adjust for "hours vary" responses
    EARNHRLY_EXCTIPS_PRED= case_when(PAIDHOUR == 2 ~ HOURWAGE, 
                               UHRSWORK1 == 0 ~ NA,
                               PAIDHOUR != 2 ~ EARNWEEK/UHRSWORK1_PRED),
    EARNHRLY2_EXCTIPS_PRED = case_when(PAIDHOUR == 2 ~ HOURWAGE2, 
                               UHRSWORK1 == 0 ~ NA,
                               PAIDHOUR != 2 ~ EARNWEEK2/UHRSWORK1_PRED),
    # Using top-code adjusted weekly hours among non-hourly workers
    EARNHRLY_EXCTIPS_TC  = case_when(PAIDHOUR == 2 ~ HOURWAGE, 
                            UHRSWORK1 == 0 ~ NA,
                            PAIDHOUR != 2 ~ EARNWEEK_TC/UHRSWORK1),
    EARNHRLY2_EXCTIPS_TC  = case_when(PAIDHOUR == 2 ~ HOURWAGE2, 
                            UHRSWORK1 == 0 ~ NA,
                            PAIDHOUR != 2 ~ EARNWEEK2_TC/UHRSWORK1),
    # Using top-code adjusted weekly hours among non-hourly workers
    # Excludes tips, overtime, commission among hourly workers, 
    # using just hourly wage rates
    EARNHRLY_EXCTIPS_TC_HRSPRED = case_when(PAIDHOUR == 2 ~ HOURWAGE, 
                            UHRSWORK1 == 0 ~ NA,
                            PAIDHOUR != 2 ~ EARNWEEK_TC/UHRSWORK1_PRED),
    EARNHRLY2_EXCTIPS_TC_HRSPRED = case_when(PAIDHOUR == 2 ~ HOURWAGE2, 
                             UHRSWORK1 == 0 ~ NA,
                             PAIDHOUR != 2 ~ EARNWEEK2_TC/UHRSWORK1_PRED),
    # Includes tips, overtime, commission among hourly workers 
    EARNHRLY_INCTIPS = EARNWEEK/UHRSWORK1,
    EARNHRLY2_INCTIPS  = EARNWEEK2/UHRSWORK1,
    EARNHRLY_INCTIPS_PRED = EARNWEEK/UHRSWORK1_PRED,
    EARNHRLY2_INCTIPS_PRED  = EARNWEEK2/UHRSWORK1_PRED,
    EARNHRLY_INCTIPS_TC = EARNWEEK_TC/UHRSWORK1,
    EARNHRLY2_INCTIPS_TC  = EARNWEEK2_TC/UHRSWORK1,
    EARNHRLY_INCTIPS_TC_HRSPRED = EARNWEEK_TC/UHRSWORK1_PRED,
    EARNHRLY2_INCTIPS_TC_HRSPRED = EARNWEEK2_TC/UHRSWORK1_PRED,
    # 
    EARNHRLY_FLAG = case_when(PAIDHOUR == 2 ~ "Hourly",
                              UHRSWORK1 == 0 ~ "None", # 987 Observartions report being paid weekly but 0 hours worked
                              PAIDHOUR != 2 ~ "Weekly"), 
    #
    EARNHRLY_TC_HRSCAP_EXCTIPS = case_when(PAIDHOUR == 2 ~ HOURWAGE, 
                                            UHRSWORK1 == 0 ~ NA,
                                            PAIDHOUR != 2 ~ EARNWEEK_TC/UHRSWORK1_PRED_CAP),
    EARNHRLY2_TC_HRSCAP_EXCTIPS  = case_when(PAIDHOUR == 2 ~ HOURWAGE2, 
                                              UHRSWORK1 == 0 ~ NA,
                                              PAIDHOUR != 2 ~ EARNWEEK2_TC/UHRSWORK1_PRED_CAP),
    EARNHRLY_TC_HRSCAP_INCTIPS = EARNWEEK_TC/UHRSWORK1_PRED_CAP,
    EARNHRLY2_TC_HRSCAP_INCTIPS = EARNWEEK2_TC/UHRSWORK1_PRED_CAP,
    # Creates birth cohort groupings for later figures
    BIRTHYEAR_DECADES = case_when(BIRTHYEAR %in% c(1927:1936) ~ "1927-1936",
                                       BIRTHYEAR %in% c(1937:1946) ~ "1937-1946",
                                       BIRTHYEAR %in% c(1947:1956) ~ "1947-1956",
                                       BIRTHYEAR %in% c(1957:1966) ~ "1957-1966",
                                       BIRTHYEAR %in% c(1967:1976) ~ "1967-1976",
                                       BIRTHYEAR %in% c(1977:1986) ~ "1977-1986",
                                       BIRTHYEAR %in% c(1987:1996) ~ "1987-1996"
         ))

# Writing out clean analytic data files, both all monthly + only ORG eligible
analytic_sample_org_elig <- analytic_sample_org %>%
  filter(ELIGORG == 1) %>%
  # Including only wage and salary workers who meet the criteria for ORG eligibility
  filter(CLASSWKR %in% c(20, 21, 22, 23, 24, 25, 27, 28))

write_rds(analytic_sample_org, "clean_data/analytic_sample_org_all.rds")
write_rds(analytic_sample_org_elig, "clean_data/analytic_sample_org_elig.rds")
write_csv(analytic_sample_org, "clean_data/analytic_sample_org_all.csv")
write_csv(analytic_sample_org_elig, "clean_data/analytic_sample_org_elig.csv")

#------------------------------------------------------------------------------

# Diagnostic plot, mean wages at age 25 with different wage measures

means_25_wagemeasures <- analytic_sample_org %>%
  filter(ELIGORG == 1) %>% filter(AGE == 25) %>% 
  group_by(BIRTHYEAR, FEMALE, YEAR) %>% 
  summarise(across(
    .cols = c(EARNHRLY, EARNWEEK_TC,
              EARNWEEK2, HOURWAGE2),
    .fns = ~ weighted.mean(., w = EARNWT, na.rm = TRUE)
  )) %>% 
  gather(KEY, VALUE, -c(BIRTHYEAR, FEMALE, YEAR)) %>%
  mutate(KEY_2 = ifelse(KEY %in% c("EARNHRLY", "HOURWAGE"), "Hourly", "Weekly")) %>%
  ggplot(aes(x = YEAR, y = VALUE, linetype = FEMALE)) +
  facet_grid(rows = vars(KEY), scales = "free") +
  geom_line() +
  theme_bw() +
  labs(title = "Weighted Means, Age 25 Wage Measures Across Years") +
  geom_vline(xintercept = 1994, color = "red", linetype = "dashed") +
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = .5)) +
  guides(linetype = guide_legend(""))

ggsave("figures/draft_paper/diagnostic_plots/means_25_wagemeasures.pdf",
       means_25_wagemeasures,
       width = 8, height = 8, dpi = 500, units = "in")

# Diagnostic table and plot, share reporting earnings weekly/hourly

table_reporting_wages_type_pct <- analytic_sample_org %>%
  filter(ELIGORG == 1) %>% 
  filter(FEMALE == "Women", EARNHRLY_FLAG != "None") %>%
  tabyl(YEAR, EARNHRLY_FLAG) %>%
  rename(Women_Hourly = Hourly, Women_Weekly = Weekly) %>%
  adorn_percentages("row") %>%
  left_join(analytic_sample_org %>%
              filter(FEMALE == "Men", EARNHRLY_FLAG!= "None") %>%
              tabyl(YEAR, EARNHRLY_FLAG) %>%
              rename(Men_Hourly = Hourly, Men_Weekly = Weekly) %>%
              adorn_percentages("row"), by = "YEAR") %>%
  mutate_if(is.numeric, round, digits = 3)

write_csv(table_reporting_wages_type_pct, 
          "figures/draft_paper/diagnostic_plots/table_reporting_wages_type_pct.csv")

reporting_wages_pct <- table_reporting_wages_type_pct %>%
  gather(key, value, -YEAR) %>%
  separate(key, c("gender", "type"), "_") %>%
  filter(type == "Hourly") %>%
  ggplot(aes(x = YEAR, y = value)) +
  geom_line() +
  theme_bw() +
  facet_wrap(~gender) +
  theme(legend.position = "bottom", plot.title = element_text(hjust = .5)) +
  labs(y = "Percent", x = "Year", 
       title = "Share of Workers Reporting Hourly (vs. Weekly) Earnings") +
  guides(linetype = guide_legend(""))

# Diagnostic plot, mean wages among those reporting earnings weekly/hourly

reporting_wages_means  <- analytic_sample_org %>%
  filter(ELIGORG == 1, EARNHRLY_FLAG != "None") %>% 
  group_by(YEAR, FEMALE, EARNHRLY_FLAG) %>%
  summarise(mean_earnings = wtd.mean(EARNHRLY, weight = EARNWT)) %>%
  ggplot(aes(x = YEAR, y = mean_earnings, linetype = EARNHRLY_FLAG)) +
  geom_line() +
  theme_bw() +
  facet_wrap(~FEMALE) +
  theme(legend.position = "bottom", plot.title = element_text(hjust = .5)) +
  labs(y = "Mean", x = "Year",
       title = "Mean Wages Among Workers Reporting Hourly/Weekly Earnings, HOUR/WEEKLY WAGE") +
  geom_vline(xintercept = 1988, linetype = "dashed", color = "red") +
  geom_vline(xintercept = 1993, linetype = "dashed", color = "red") +
  guides(linetype = guide_legend("Earnings Reported")) +
  ylim(20, 60)

ggsave("figures/draft_paper/diagnostic_plots/type_reporting.pdf",
       grid.arrange(reporting_wages_pct, reporting_wages_means, ncol = 1),
       width = 8, height = 8, dpi = 500, units = "in")
