#------------------------------------------------------------------------------
# PROJECT: GENDER PAY GAP STARTING POINTS AND LIFE COURSE DIVERGENCE
# FILE: GENERATING ORG ANALYTIC SAMPLE FROM RAW IPUMS DATA
# AUTHOR: NINO CRICCO
#------------------------------------------------------------------------------
source("jobs/0-helperfunctions.R")
#------------------------------------------------------------------------------
# READ IN RAW DATA
#------------------------------------------------------------------------------
# DDI codebook to read in raw IPUMS data

# To load data, you must download both the extract and DDI from IPUMS
# also set the wd to the folder with these files (or change the path below).

ddi_monthly <- ipumsr::read_ipums_ddi("raw_data/cps_00023.xml")

data_monthly <- ipumsr::read_ipums_micro(
  ddi_monthly,
  vars = c(
    "YEAR", # Survey Year
    "MISH", # Month in CPS sample, used to identify ORG interview months 
    "AGE", # Age
    "IND1990", # 1990 Industry codes
    "CLASSWKR", # Indicates whether employer is self-employed, public/private sector, armed forces, or worked without pay
    "SEX", # Sex
    "EDUC", # IPUMS educational attainment recode
    "ELIGORG", # Indicator for wtr R was eligible for ORG (in month 4 or 8 of CPS interview + wage or salary worker)
    "HOURWAGE2", # R earnings per-hour in current job if R paid by the hour (2 in PAIDHOUR)
    "EARNWEEK2", # R earnings per week at current job before deductions
    "PAIDHOUR", # Indicator for wtr R paid by the hour for their current job
    "UHRSWORK1", # Usual hours per week R reports being at their main job, monthly survey
    "UHRSWORKORG", # Usual hours per week R reports at main job, for ORG hourly workers only (hours worked at hourly rate)
    "WKSTAT", # Census recode for part-time or full-time employment status
    "EARNWT", # Weight for the ORG
    "HISPAN", # Hispanic/Spanish/Latino ancestry, heritage, country of birth
    "RACE", # Racial category
    "MARST", # Current marital status
    "NATIVITY" # Native or foreign born
    )) %>%
  filter(YEAR >= 1982, YEAR <= 2024) %>% # Selecting observation years
  filter(MISH %in% c(4, 8)) %>% # Selecting months eligible for ORG interview
  filter(AGE >= 25 & AGE <= 55) # Selecting age window

#------------------------------------------------------------------------------
# RECODING RAW DATA
#------------------------------------------------------------------------------
# KEY NOTES: 
# - IPUMS reports Hourly Wages and Weekly Wages in two different variables, 
#   HOURWAGE/EARNWEEK and HOURWAGE2/EARNWEEK2. Starting in April 2023, the 
#   Census Bureau began rounding hourly and weekly earnings as a privacy 
#   protection measure. HOURWAGE2/EARNWEEK2 imposes these rounding criteria on
#   pre-April 2023 measures to provide comparable earnings data. To include 
#   2024 measures, we use these second variables (see IPUMS documentation for 
#   more details at https://cps.ipums.org/cps-action/variables/group/org_org).
#------------------------------------------------------------------------------
# Read in CPI adjustment spreadsheet
# Generated by IPUMS, accesible at https://cps.ipums.org/cps/cpi99.shtml
cpi99 <- read_csv("raw_data/cpi99.csv")

analytic_sample <- data_monthly %>% 
  # Merging in CPI inflation adjustment 
  left_join(., cpi99, by = c("YEAR" = "year")) %>%
  mutate(
    # Estimating Birth Cohort using survey year & age- Rs could also belong to prior BC 
    BIRTHYEAR = YEAR-AGE, 
    FEMALE = ifelse(SEX == 2, "Women", "Men"),
    EDUC = ifelse(EDUC == 999, NA, EDUC),
    EDUC2 = ifelse(EDUC >= 110, "BA+", "<BA"),
    HOURWAGE2 = na_codes(HOURWAGE2, 999.99),
    EARNWEEK2 = na_codes(EARNWEEK2, 999999.99), 
    EARNWEEK2_0_FLAG = ifelse( # Flagging Rs who report 0 weekly earnings
      complete.cases(EARNWEEK2) & EARNWEEK2 == 0, TRUE, FALSE), 
    UHRSWORK1_HRSVARY_FLAG = ifelse(UHRSWORK1 == 997, TRUE, FALSE), # Indicator for whether R reported hours vary
    UHRSWORK1 = na_codes(UHRSWORK1, 999, 997),
    WKSTAT_SUM = case_when(WKSTAT %in% c(10:15) ~ "ft", 
                           WKSTAT %in% c(20:42) ~ "pt", 
                           WKSTAT %in% c(50, 60)~ "unemp"), 
    EARNWT = EARNWT/12,
    # We use Race and Hispanic/Latino origin/descent to code for Race/Ethnicity
    # Starting in 2003, CPS allowed Rs to select more than 1 Race, expanding the number of codes
    # We code Rs who report >1 Race, and who do not report being Black, White, or Latino as "Other"
    RACEETH = case_when(HISPAN %!in% c(0, 901, 902) ~ "Latino", 
                        RACE == 200 ~ "Black", 
                        RACE == 100 ~ "White",
                        TRUE ~ "Other"), 
    # We use marital status and nativity only to predict hours among Rs reporting hours vary (more below)
    MARRIED = case_when(MARST %in% c(1,2) ~ "married", 
                        MARST == 6 ~ "never.married", 
                        TRUE ~ "prev.married"), 
    FBORN = factor(ifelse(NATIVITY == 5, 1, 0))) %>%
  # Identifying EARNWEEK top-code values by year (and Month of Interview, given later dynamic topcodes)
  # More information on CPS top-coding procedures and how we handle them in sections below
  group_by(YEAR, MISH) %>%
  mutate(across(
    c(EARNWEEK2),
    list(TOPCODE = ~ max(.x, na.rm = TRUE),
         TOPCODE_FLAG = ~ as.integer(.x == max(.x, na.rm = TRUE))),
    .names = "{.col}_{.fn}"
  )) %>%
  ungroup() %>%
  # Select only respondents who report being ORG-eligible, based on being a wage/salary worker Age 15+ in an ORG(MISH 4 and 8)
  filter(ELIGORG == 1) %>%
  # Including only wage and salary workers who meet the criteria for ORG eligibility
  # IPUMS recommends users impose CPS eligibility criteria in addition to just using the ELIGORG flag 
  # see documentation here: https://cps.ipums.org/cps-action/variables/UHRSWORKORG#comparability_section
  filter(CLASSWKR %in% c(20, 21, 22, 23, 24, 25, 27, 28)) %>%
  filter(EARNWEEK2_0_FLAG == F) # We exclude Rs who report zero earnings

#------------------------------------------------------------------------------
# RECODING MAIN EARNINGS VARIABLES
#------------------------------------------------------------------------------
# KEY NOTES:
#   - Prior research notes important challenges that come with estimating 
#   consistent hourly wage series using the ORG due to the design of the CPS 
#   and changes to those designs (see Schmitt 2003, linked below): 
#     https://ceprdata.s3.amazonaws.com/data/cps/CEPR_ORG_Wages.pdf
#   We follow the best practices outlined in this paper, which include
#   1) Imputing weekly hours for Rs reporting "hours vary" starting in 1994
#     using a regression-based imputation procedure
#   2) Estimating mean earnings above top-code values, which change in 1989, 
#     1994, 1998, and 2023 using a log-normal imputation
#   3) Using the hourly wage series that excludes overtime, tip, and commission
#     earnings for Rs paid hourly 
#   - Our results to these different specifications of the hourly wage series, 
#   as we show in the appendix. Since our interest is in trends that precede
#   1994, we exclude tips, overtime, and commissions by using just hourly 
#   wages for Rs who report being paid hourly, and weekly earnigns (which 
#   include tips, commision, and overtime) for Rs reporting weekly earnings
#   - For more details, see the IPUMS documentation here:
#     https://cps.ipums.org/cps-action/variables/EARNWEEK#description_section
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# IMPUTING HOURS WORKED FOR RESPONDENTS WHO REPORT HOURS VARY AFTER 1994
#------------------------------------------------------------------------------
# KEY NOTES: 
#   -There are a small number of Rs (1034, .02% of the overall sample) who 
#   report zero hours in the monthly usual hours worked variable but who report
#   their wages hourly. For these Rs, we technically don't use their hours to 
#   compute their hourly wage for our primary specification, which uses just the
#   hourly wage, so in theory we could include them. When we include tips,
#   overtime, and commissions, though, we do use their hours. For comparability 
#   across these different specifications, we drop these individuals from the
#   sample in this section in line 204: (filter(UHRSWORK1_PRED_0_FLAG == F))
#------------------------------------------------------------------------------
# Diagnostics figure to show what % of Rs report "hrs vary" by year & sex 
fig_diag_hrsvary <- analytic_sample %>%
  group_by(FEMALE, YEAR) %>%
  summarise(share_hrsvary = wtd.mean(UHRSWORK1_HRSVARY_FLAG, weight = EARNWT)) %>%
  ggplot(aes(
    x = YEAR, y = share_hrsvary, linetype = FEMALE)) +
  geom_line() +
  theme_bw() +
  labs(title = "Diagnostics Plot: Workers Reporting Hours Vary, CPS Outgoing Rotation Group",
       y = "Share", x = "Year") +
  theme(legend.position = "bottom", 
        plot.title = element_text(hjust = .5),
        legend.title = element_blank()) +
  geom_vline(xintercept = 1994, color = "red", linetype = "dashed")

# To estimate UHRSWORK1 among those reporting hours vary, we regress UHRSWORK1
# on Age, Race, Education, Marital Status, and Nativity separately by Sex and 
# full-time/part time status among those who do not report hours vary, then 
# impute UHRSWORK1 with  the predicted values from this regression on those 
# who do report hours vary 

# Use Hours vary flag to select those who do not report hours vary
hrsvary_estimation <- analytic_sample %>%
  filter(UHRSWORK1_HRSVARY_FLAG != 1)

# Create nested dataframes by group for men, women by reported ft/pt status
model_hrsvary <- hrsvary_estimation %>%
  group_by(FEMALE, WKSTAT_SUM) %>%
  nest() %>%
  # Fit regression model for each sex * work status group
  mutate(
    model = map(
      data, ~ lm(UHRSWORK1 ~ AGE + RACEETH + MARRIED + FBORN + EDUC, data = .x))
  )

# Generate predicted hours among Rs who report hours vary using these models
hrsvary_data <- analytic_sample %>%
  filter(UHRSWORK1_HRSVARY_FLAG == 1) %>% # Selects Rs who report hours vary
  group_by(FEMALE, WKSTAT_SUM) %>% # Nests by sex * work status group
  nest() %>%
  # Join with model data
  left_join(model_hrsvary %>% select(-data), by = c("FEMALE", "WKSTAT_SUM")) %>%
  # Generate predictions
  mutate(predictions = map2(model, data, predict)) 

# Combine the two dataframes for Rs reporting hours + Rs reporting hours vary
analytic_sample_hrsvary <- bind_rows(
  hrsvary_estimation %>% mutate(UHRSWORK1_PRED = UHRSWORK1),
  hrsvary_data %>% mutate(UHRSWORK1_PRED = predictions)) %>%
  arrange(row_number()) %>%
  mutate(
    # Additional variable capping hours worked (obs or predicted) at 40
    UHRSWORK1_PRED_CAP = ifelse(UHRSWORK1_PRED > 40, 40, UHRSWORK1_PRED), 
    UHRSWORK1_PRED = as.numeric(zap_labels(UHRSWORK1_PRED)),
    UHRSWORK1_PRED_0_FLAG = ifelse(UHRSWORK1_PRED == 0, T, F)) %>%
  # Dropping individuals reporting zero usual hours worked (see note above)
  filter(UHRSWORK1_PRED_0_FLAG == F)
 
# Diagnostic plot comparing mean hours worked with list-wise deletion of Rs
# reporting hours vary vs. imputing hours worked
fig_hrsvary_pred <- analytic_sample_hrsvary %>%
  group_by(FEMALE, YEAR) %>%
  summarise(UHRSWORK1_PRED = wtd.mean(UHRSWORK1_PRED, weight = EARNWT), 
            UHRSWORK1 = wtd.mean(UHRSWORK1, weight = EARNWT)) %>%
  gather(key, value, -c(FEMALE, YEAR)) %>% 
  ggplot(aes(x = YEAR, y = value, linetype = key)) +
  geom_line() +
  theme_bw() +
  facet_wrap(~FEMALE) +
  labs(title = "Diagnostics Plot: Mean Usual Hours Worked, List-wise Deletion 
       and Imputation, CPS Outgoing Rotation Group",
       y = "Usual Hours Worked per Week", x = "Year") +
  theme(legend.position = "bottom", 
        plot.title = element_text(hjust = .5),
        legend.title = element_blank()) +
  geom_vline(xintercept = 1994, color = "red", linetype = "dashed")

ggsave("figures/draft_paper/diagnostic_plots_13.06.25/hoursvary.pdf",
       grid.arrange(fig_diag_hrsvary, fig_hrsvary_pred, ncol = 1),
       width = 10, height = 10, dpi = 500, units = "in")

#------------------------------------------------------------------------------
# ESTIMATING MEAN WAGES ABOVE THE TOP-CODE
#------------------------------------------------------------------------------
# KEY NOTES:
#   - The CPS changed their top-coding rules through our series in  1989, 1998, 
#   and 2023. While a small percentage of Rs are top-coded after each change, 
#   the % of people top-coded grows year-to-year, prompting adjustments (see 
#   diagnostic plots below). To adjust for these changes in top-coding, we 
#   estimate the mean above the top-code in each year and assign that mean to
#   all top-coded R's. To estimate this mean, we follow the procedure outlined
#   in Schmitt (2003), which assumes that weekly earnings data are log-normally
#   distributed. We first model the distribution of earnings as log-normal and
#   estimate the mean of the distribution above the top-code conditional on
#   the log-normal parameters estimated from the uncensored data. 
#------------------------------------------------------------------------------
# Diagnostic plot, share of workers reporting weekly earnings above the topcode
fig_diag_topcode <- analytic_sample_hrsvary %>%
  group_by(FEMALE, YEAR, PAIDHOUR) %>%
  mutate(PAIDHOUR = ifelse(PAIDHOUR == 2, "Hourly", "Weekly")) %>%
  summarise(
    SHARE_TOPCODED_EARNWEEK2 = wtd.mean(
      EARNWEEK2_TOPCODE_FLAG, weight = EARNWT)) %>%
  ggplot(aes(x = YEAR, y = SHARE_TOPCODED_EARNWEEK2,
             color = FEMALE, linetype = )) +
  geom_line() +
  geom_point() +
  theme_bw() +
  facet_grid(rows = vars(PAIDHOUR), scales = "free") +
  labs(title = "Diagnostics Plot: Workers w/ Top-Coded Weekly Earnings, ORG",
       y = "Share", x = "Year") +
  theme(legend.position = "bottom", 
        plot.title = element_text(hjust = .5),
        legend.title = element_blank()) +
  geom_vline(xintercept = 1989, color = "red", linetype = "dashed") +
  geom_vline(xintercept = 1998, color = "red", linetype = "dashed") +
  geom_vline(xintercept = 2023, color = "red", linetype = "dashed")

analytic_sample_recoded_topcode <- analytic_sample_hrsvary %>% 
  group_by(YEAR, MISH) %>% # Computes estimates for each year/ORG month (top code values change by month in later years)
  mutate(
    mu = ifelse(EARNWEEK2_TOPCODE_FLAG == 1, # Estimates mean of full log-normal earnings distribution
                mean(log(EARNWEEK2), na.rm = TRUE), NA_real_),
    sd = ifelse(EARNWEEK2_TOPCODE_FLAG == 1,
                 sd(log(EARNWEEK2),  na.rm = TRUE), NA_real_), # Estimates sd of full log-normal earnings distribution
    lt = log(EARNWEEK2_TOPCODE), # Takes the log of the threshold
    t1 = exp(mu + sd^2 / 2), # Uses parameters from uncensored data to estimate mean of the uncensored distribution
    t2 = 1 - pnorm((lt - mu - sd^2) / sd), # Estimates probability mass above the threshold with parameters
    t3 = 1 - pnorm((lt - mu) / sd), # Observed probability mass above the threshold
    EARNWEEK2_TC = ifelse(
      EARNWEEK2_TOPCODE_FLAG == 1, t1 * t2 / t3, # Integrates across the tail of the lognormal
      EARNWEEK2)
    ) %>% 
  ungroup() %>% 
  select(-c(mu, sd, lt, t1, t2, t3)) # Drops these ancillary variables

# Diagnostic plot, mean earnings w/topcode vs. adjusting topcode
fig_mean_earnings_topcode_adj <- analytic_sample_recoded_topcode %>%
  group_by(FEMALE, YEAR, PAIDHOUR) %>%
  summarise(EARNWEEK2_TC = wtd.mean(EARNWEEK2_TC, weight = EARNWT), 
            EARNWEEK2 = wtd.mean(EARNWEEK2, weight = EARNWT)) %>%
  mutate(PAIDHOUR = ifelse(PAIDHOUR == 2, "Hourly", "Weekly")) %>%
  gather(KEY, VALUE, -c(FEMALE, YEAR, PAIDHOUR)) %>%
  ggplot(aes(x = YEAR, y = VALUE, linetype = PAIDHOUR, 
             color = KEY)) +
  geom_line() +
  geom_point() +
  theme_bw() +
  facet_wrap(~FEMALE) + 
  labs(title = "Diagnostics Plot: Mean Weekly Earnigns w/ Top-Code Adjustment, ORG",
       y = "Weekly Earnigns", x = "Year") +
  theme(legend.position = "bottom", 
        plot.title = element_text(hjust = .5),
        legend.title = element_blank()) +
  geom_vline(xintercept = 1989, color = "red", linetype = "dashed") +
  geom_vline(xintercept = 1994, color = "red", linetype = "dashed") +
  geom_vline(xintercept = 1998, color = "red", linetype = "dashed")

ggsave("figures/draft_paper/diagnostic_plots_13.06.25/topcode.pdf",
       grid.arrange(fig_diag_topcode, fig_mean_earnings_topcode_adj, ncol = 1),
       width = 8, height = 8, dpi = 500, units = "in")

analytic_sample_org <- analytic_sample_recoded_topcode %>%
  mutate(
    # Create different variables for different earnings series
    HOURWAGE2_RAW = HOURWAGE2, # raw IPUMS variables
    EARNWEEK2_RAW = EARNWEEK2,# raw IPUMS variables
    # Adding IPUMS adjustment factor to convert to 2023 dollars
    # from here: https://cps.ipums.org/cps/cpi99.shtml
    HOURWAGE2 = HOURWAGE2 * cpi1999 * 1.829, 
    EARNWEEK2 = EARNWEEK2 * cpi1999 * 1.829,
    # Adjusts EARNWEEK w/ estimated top-code adjustment to 2023 dollars
    EARNWEEK2_TC = EARNWEEK2_TC * cpi1999 * 1.829,
    # Using Wage for hourly workers, Weekly Earnings/ Usual Weekly hours for rest
    # Note: this variable excludes tips, overtime, and commissions for hourly workers,
    # but includes them for weekly workers
    EARNHRLY2_EXCTIPS = case_when(PAIDHOUR == 2 ~ HOURWAGE2, 
                              UHRSWORK1 == 0 ~ NA,
                              PAIDHOUR != 2 ~ EARNWEEK2/UHRSWORK1),
    # Using predicted weekly hours among non-hourly workers to adjust for "hours vary" responses
    EARNHRLY2_EXCTIPS_HRSPRED = case_when(PAIDHOUR == 2 ~ HOURWAGE2, 
                               UHRSWORK1 == 0 ~ NA,
                               PAIDHOUR != 2 ~ EARNWEEK2/UHRSWORK1_PRED),
    # Using top-code adjusted weekly hours among non-hourly workers
    EARNHRLY2_EXCTIPS_TC  = case_when(PAIDHOUR == 2 ~ HOURWAGE2, 
                            UHRSWORK1 == 0 ~ NA,
                            PAIDHOUR != 2 ~ EARNWEEK2_TC/UHRSWORK1),
    # Using top-code adjusted weekly hours among non-hourly workers
    # Excludes tips, overtime, commission among hourly workers
    EARNHRLY2_EXCTIPS_TC_HRSPRED = case_when(PAIDHOUR == 2 ~ HOURWAGE2, 
                             UHRSWORK1 == 0 ~ NA,
                             PAIDHOUR != 2 ~ EARNWEEK2_TC/UHRSWORK1_PRED),
    # Includes tips, overtime, commission among hourly workers 
    EARNHRLY2_INCTIPS  = EARNWEEK2/UHRSWORK1,
    EARNHRLY2_INCTIPS_HRSPRED  = EARNWEEK2/UHRSWORK1_PRED,
    EARNHRLY2_INCTIPS_TC  = EARNWEEK2_TC/UHRSWORK1,
    EARNHRLY2_INCTIPS_TC_HRSPRED = EARNWEEK2_TC/UHRSWORK1_PRED,
    # Use Paid Hourly variable and Usual hours to create indicator variable
    EARNHRLY_FLAG = case_when(PAIDHOUR == 2 ~ "Hourly",
                              UHRSWORK1 == 0 ~ "None", # 987 Observartions report being paid weekly but 0 hours worked
                              PAIDHOUR != 2 ~ "Weekly"), 
    # Calculating hourly wage when capping weekly hours at 40 hours
    EARNHRLY2_TC_HRSCAP_EXCTIPS  = case_when(PAIDHOUR == 2 ~ HOURWAGE2, 
                                              UHRSWORK1 == 0 ~ NA,
                                              PAIDHOUR != 2 ~ EARNWEEK2_TC/UHRSWORK1_PRED_CAP),
    EARNHRLY2_TC_HRSCAP_INCTIPS = EARNWEEK2_TC/UHRSWORK1_PRED_CAP,
    # Creates birth cohort groupings for later figures
    BIRTHYEAR_DECADES = case_when(BIRTHYEAR %in% c(1927:1936) ~ "1927-1936",
                                       BIRTHYEAR %in% c(1937:1946) ~ "1937-1946",
                                       BIRTHYEAR %in% c(1947:1956) ~ "1947-1956",
                                       BIRTHYEAR %in% c(1957:1966) ~ "1957-1966",
                                       BIRTHYEAR %in% c(1967:1976) ~ "1967-1976",
                                       BIRTHYEAR %in% c(1977:1986) ~ "1977-1986",
                                       BIRTHYEAR %in% c(1987:1996) ~ "1987-1996"
         ))

#------------------------------------------------------------------------------
# WRITING ANALYTIC SAMPLE TO THE CLEAN DATA DIRECTORY
#------------------------------------------------------------------------------
write_rds(analytic_sample_org, "clean_data/analytic_sample_org.rds")
write_csv(analytic_sample_org, "clean_data/analytic_sample_org.csv")

#------------------------------------------------------------------------------
# ADDITIONAL DIAGNOSTIC PLOTS
#------------------------------------------------------------------------------
# Diagnostic plot, mean wages at age 25 with different wage measures
means_cohorts_25 <- analytic_sample_org %>%
  filter(ELIGORG == 1) %>% filter(AGE == 25) %>% 
  group_by(BIRTHYEAR, FEMALE, YEAR) %>% 
  summarise(across(
    .cols = c(EARNHRLY2_EXCTIPS_TC_HRSPRED),
    .fns = ~ weighted.mean(., w = EARNWT, na.rm = TRUE)
  )) %>% 
  gather(KEY, VALUE, -c(BIRTHYEAR, FEMALE, YEAR)) %>%
  mutate(KEY_2 = ifelse(KEY %in% c("EARNHRLY", "HOURWAGE"), "Hourly", "Weekly")) %>%
  ggplot(aes(x = YEAR, y = VALUE, linetype = FEMALE)) +
  facet_grid(rows = vars(KEY), scales = "free") +
  geom_line() +
  theme_bw() +
  labs(title = "Weighted Means, Age 25 Across Years") +
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = .5)) +
  guides(linetype = guide_legend(""))

ggsave("figures/draft_paper/diagnostic_plots_13.06.25/means_25_wagemeasures.pdf",
       means_cohorts_25,
       width = 8, height = 8, dpi = 500, units = "in")

# Diagnostic table and plot, share reporting earnings weekly/hourly
table_reporting_wages_type_pct <- analytic_sample_org %>%
  filter(FEMALE == "Women", EARNHRLY_FLAG != "None") %>%
  tabyl(YEAR, EARNHRLY_FLAG) %>%
  rename(Women_Hourly = Hourly, Women_Weekly = Weekly) %>%
  adorn_percentages("row") %>%
  left_join(analytic_sample_org %>%
              filter(FEMALE == "Men", EARNHRLY_FLAG!= "None") %>%
              tabyl(YEAR, EARNHRLY_FLAG) %>%
              rename(Men_Hourly = Hourly, Men_Weekly = Weekly) %>%
              adorn_percentages("row"), by = "YEAR") %>%
  mutate_if(is.numeric, round, digits = 3)

write_csv(table_reporting_wages_type_pct, 
          "figures/draft_paper/diagnostic_plots_13.06.25/table_reporting_wages_type_pct.csv")

reporting_wages_pct <- table_reporting_wages_type_pct %>%
  gather(key, value, -YEAR) %>%
  separate(key, c("gender", "type"), "_") %>%
  filter(type == "Hourly") %>%
  ggplot(aes(x = YEAR, y = value)) +
  geom_line() +
  theme_bw() +
  facet_wrap(~gender) +
  theme(legend.position = "bottom", plot.title = element_text(hjust = .5)) +
  labs(y = "Percent", x = "Year", 
       title = "Share of Workers Reporting Hourly (vs. Weekly) Earnings") +
  guides(linetype = guide_legend(""))

# Diagnostic plot, mean wages among those reporting earnings weekly/hourly
reporting_wages_means  <- analytic_sample_org %>%
  filter(EARNHRLY_FLAG != "None") %>%
  group_by(YEAR, FEMALE, EARNHRLY_FLAG) %>%
  summarise(mean_earnings = wtd.mean(
    EARNHRLY2_EXCTIPS_TC_HRSPRED, weight = EARNWT)) %>%
  ggplot(aes(x = YEAR, y = mean_earnings, linetype = EARNHRLY_FLAG)) +
  geom_line() +
  theme_bw() +
  facet_wrap(~FEMALE) +
  theme(legend.position = "bottom", plot.title = element_text(hjust = .5)) +
  labs(y = "Mean", x = "Year",
       title = "Mean Wages Among Workers Reporting Hourly/Weekly Earnings, HOUR/WEEKLY WAGE") +
  geom_vline(xintercept = 1988, linetype = "dashed", color = "red") +
  geom_vline(xintercept = 1993, linetype = "dashed", color = "red") +
  guides(linetype = guide_legend("Earnings Reported"))

ggsave("figures/draft_paper/diagnostic_plots_13.06.25/type_reporting.pdf",
       grid.arrange(reporting_wages_pct, reporting_wages_means, ncol = 1),
       width = 8, height = 8, dpi = 500, units = "in")